/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Api: () => import('#controllers/api_controller'),
  Categories: () => import('#controllers/categories_controller'),
  CategoryClimbers: () => import('#controllers/category_climbers_controller'),
  CgApi: () => import('#controllers/cg_api_controller'),
  Cg: () => import('#controllers/cg_controller'),
  Climbers: () => import('#controllers/climbers_controller'),
  Config: () => import('#controllers/config_controller'),
  Images: () => import('#controllers/images_controller'),
  Live: () => import('#controllers/live_controller'),
  Logs: () => import('#controllers/logs_controller'),
  Timer: () => import('#controllers/timer_controller'),
}
