/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CategorySchema extends BaseModel {
  static $columns = ['bgImageUrl', 'createdAt', 'id', 'ifscCategoryRoundId', 'name', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column()
  declare bgImageUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ifscCategoryRoundId: number | null
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategoryClimberSchema extends BaseModel {
  static $columns = ['categoryId', 'climberId', 'createdAt', 'id', 'order', 'place', 'results', 'route', 'score', 'updatedAt'] as const
  $columns = CategoryClimberSchema.$columns
  @column()
  declare categoryId: number
  @column()
  declare climberId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare order: number | null
  @column()
  declare place: number | null
  @column()
  declare results: number | null
  @column()
  declare route: string | null
  @column()
  declare score: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClimberGroupSchema extends BaseModel {
  static $columns = ['climberId', 'createdAt', 'group', 'id', 'routeIdx', 'updatedAt'] as const
  $columns = ClimberGroupSchema.$columns
  @column()
  declare climberId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare group: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare routeIdx: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClimberRouteResultSchema extends BaseModel {
  static $columns = ['categoryClimberId', 'createdAt', 'id', 'order', 'route', 'top', 'topTries', 'updatedAt', 'zone', 'zoneTries'] as const
  $columns = ClimberRouteResultSchema.$columns
  @column()
  declare categoryClimberId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare order: number
  @column()
  declare route: string
  @column()
  declare top: boolean | null
  @column()
  declare topTries: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zone: boolean | null
  @column()
  declare zoneTries: number | null
}

export class ClimberSchema extends BaseModel {
  static $columns = ['createdAt', 'firstName', 'flagUrl', 'id', 'ifscId', 'lastName', 'nationality', 'tag', 'updatedAt'] as const
  $columns = ClimberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare firstName: string | null
  @column()
  declare flagUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ifscId: number | null
  @column()
  declare lastName: string | null
  @column()
  declare nationality: string | null
  @column()
  declare tag: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ConfigOptionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'option', 'updatedAt', 'value'] as const
  $columns = ConfigOptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare option: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
